# Generated by Django 5.2 on 2025-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='available_times',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialties',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
