# Generated by Django 5.2 on 2025-04-26 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_friends_profile_available_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connected_trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='profiles.profile'),
        ),
    ]
