# Generated by Django 5.2 on 2025-04-18 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='rate_per_session',
        ),
        migrations.AddField(
            model_name='trainer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='available_times',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialties',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
