# Generated by Django 5.2 on 2025-04-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_clientcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientComment',
        ),
    ]
