# Generated by Django 5.2 on 2025-04-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_connected_trainer'),
        ('trainers', '0007_trainercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionbooking',
            name='trainer',
        ),
        migrations.AlterField(
            model_name='trainercomment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='trainer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
