# Generated by Django 5.2 on 2025-04-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_challenge_challengeprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeprogress',
            name='challenge',
        ),
        migrations.AlterUniqueTogether(
            name='challengeprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='challengeprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='ChallengeProgress',
        ),
    ]
